services:
  frontend-react:
    build:
      context: .
    image: node-react_img
    ports:
      - "9000:9000"
    volumes:
      # - ./react-pract:/app
      - ./frontend-react:/app/frontend-react
      - "bot-craft_frontend_node_volumes:/app/frontend-react/node_modules"

    
    restart: unless-stopped
    
    stdin_open: true
    tty: true
        
    container_name: twp-frontend-react
    hostname: twp-frontend-react

volumes:
  bot-craft_frontend_node_volumes:
    name: bot-craft_frontend_node_volumes
    # external: true